### ISSUE TITLE
[BUG] - Mock engine returns 1 or 2 Entity instances which can cause an error from router

### ISSUE THREAD

**Issue by michael-watson** [apollographql/apollo-workbench-vscode#129]
When running mocks and executing queries that will return an Entity and another subgraphs fields for that Entity, `__resolveReference` will provide 1 instance of the Entity and the `__entities` entry point of the second Subgraph might return 2 Entity instances which would cause an error at the graph router when trying to assemble the data sets together.

The fix for this issue is to have workbench's mock engine mock the `__entities` and/or the `__resolveReference` resolver based on what entities are defined in the overall graph. I believe this is due to the `__entities` resolver returning an Array which `apollo-server` defaults mocking to randomizing either 1 or 2 results. It will require some debugging to dig deep into this.

**Comment by dchambers** [comment]
@michael-watson, I suspect I just ran into the same thing when trying to use the mock function of Apollo Workbench:

```
Expected \"data._entities\" to contain 1 elements
```

**Comment by michael-watson** [comment]
This is working in the most recent release. I replicated with using:

```
federation_version: '=2.4.7'
subgraphs:
  foo:
    routing_url: http://localhost:4001
    schema:
      file: ./foo.graphql
      workbench_design: ./foo.graphql
  bar:
    routing_url: http://localhost:4002
    schema:
      file: ./bar.graphql
      workbench_design: ./bar.graphql
operations: {}
```

```
#Foo Schema
extend schema
  @link(url: "https://specs.apollo.dev/federation/v2.3", import: ["@key"])

type Query {
  foos: [Foo]
}

type Foo @key(fields: "id") {
  id: ID!
  bars: [Bar]
}

type Bar @key(fields: "id") {
  id: ID
}
```

```
#Bar schema
extend schema
  @link(url: "https://specs.apollo.dev/federation/v2.3", import: ["@key"])

type Bar @key(fields: "id") {
  id: ID!
  name: String
}
```
